### ISSUE TITLE
skylineOSP - fork of skylineOS

### ISSUE THREAD

**Issue by ismaelestalayo** [mmatyas/pegasus-theme-gallery-db#17]
Hey, wanted to add my fork of skylineOS I made a few months ago where I added a few extra buttons and features like zoom levels, "systems" view, favorites...

https://github.com/ismaelestalayo/skylineOSP

**Comment by mmatyas** [comment]
Ok, thanks!

**Comment by ismaelestalayo** [comment]
Thanks for the quick response.
How does the website scrap the images of the theme, does it search for particular filenames or something?

**Comment by mmatyas** [comment]
It uses the `assets.screenshots` defined in `theme.cfg`, in your case

- assets/images/screenshot_bar_end.png
- assets/images/screenshot_allsoft_ps1.png

but these files don't exist in the repository, so the profile picture is used. Let me know if you make some changes and I'll update the site.

**Comment by ismaelestalayo** [comment]
Oh of course! I didnt change those after the fork! 🤦🏻‍♂️ 
I just made a quick commit with the correct screenshot paths. I would love if you could update the site.
Thanks! ❤️

**Comment by mmatyas** [comment]
Ok, should be up to date in a few minutes!
