### ISSUE TITLE
Sleipnir - New theme (fork of retromega-next)

### ISSUE THREAD

**Issue by y-muller** [mmatyas/pegasus-theme-gallery-db#19]
Hi. New theme at [https://github.com/y-muller/retromega-sleipnir](https://github.com/y-muller/retromega-sleipnir)
Based on retromega-next and aimed at large handhelds.

**Comment by mmatyas** [comment]
Nice work! I'm away for the weekend, but I can merge this next Monday. Feel free to ping me if I forget about it!

**Comment by mmatyas** [comment]
Added, thanks!
