### ISSUE TITLE
Add a fork of the Flixnet theme

### ISSUE THREAD

**Issue by ZagonAb** [mmatyas/pegasus-theme-gallery-db#23]
Hello I would like to add this modification of the Flixnet theme. I leave the github here: https://github.com/ZagonAb/FlixNet_Plus
I don't know if it's correct or not!
Could you help me?

**Comment by mmatyas** [comment]
Nice, thanks! Just one thing, there's no screenshot included inside the github repo. In the original Flixnet, this is stored at `.meta/screenshot.jpg`, but if you wish, you can change the path in the `theme.cfg` file.

**Comment by ZagonAb** [comment]
ok I will try to do it and I will communicate it here.. thank you!

**Comment by ZagonAb** [comment]
I managed to put the screenshot in "assets/screenshot.png" and edited the theme.cfg file. I still don't quite understand github.
If something is missing, I'd like to know.
Thank you.!

**Comment by mmatyas** [comment]
Ok, looks good! The theme should be online in a few minutes.
