### ISSUE TITLE
Personal fork of gameOS!

### ISSUE THREAD

**Issue by HomeStarRunnerTron** [mmatyas/pegasus-theme-gallery-db#24]
Hi-hi! :  ) Thank you immensely for all of your help over on the primary GitHub. After months of work, I've amassed a little mountainous molehill of nitpicky fixes for things in gameOS, and I've made it the first thing I've successfully put on GitHub, woaaah.

_Tah-dah_, I call it gameOS - Fire & sKye: https://github.com/HomeStarRunnerTron/gameOS-fire-sKye

It'd be a serious honour to be added to the database, if that's possible. :  ) Oh-- also, while I'm here in "Issues", I see that the Theme Gallery separates uppercase titles from lowercase titles. Is it best to leave that as-is, or maybe they can be sorted together for a nice, clean A-Z? Just a thought.

**Comment by mmatyas** [comment]
Added, thanks! Also thanks for the suggestion, it should be now sorted from A to Z properly.

**Comment by HomeStarRunnerTron** [comment]
Wow, crazy-fast, dude! Grid organization looks slick. Happy Labour Day to you, wherever you are. Quick thing-- could you add [my screenshot](https://github.com/HomeStarRunnerTron/gameOS-fire-sKye/blob/master/assets/images/screenshot.png) as the preview image, instead of my avatar? Just want people to be able to see what they're getting. ^_^

**Comment by HomeStarRunnerTron** [comment]
Oh-- I see, I had to add it to my theme.cfg! [Donezo](https://github.com/HomeStarRunnerTron/gameOS-fire-sKye/commit/9aeb5805dbdd70ec2065d19679d000bf4e1831a8) -- glad it was discussed in a previous Issue.

**Comment by mmatyas** [comment]
Ok, should be up to date now!

**Comment by HomeStarRunnerTron** [comment]
_Whew_, that's a real relief to see it displayed correctly-- I know the people who just display their avatar confused _me_ at first, so I didn't want to personally add to that confusion, haha. :  ) All the best, and thanks to your launcher, I've been actually making time to play games and read books. Real change for the better. ^_^
