### ISSUE TITLE
Theme for Pegasus Frontend

### ISSUE THREAD

**Issue by VGmove** [mmatyas/pegasus-theme-gallery-db#25]
Hello!

This is my new theme for Pegasus Frontend.
Please add to the gallery.

https://github.com/VGmove/EasyLaunch

**Comment by mmatyas** [comment]
Hi, sorry for the late reply! There was a national holiday this weekend. I've added the theme, thanks!

**Comment by VGmove** [comment]
Thank you! I really like Pegasus Frontend
