### ISSUE TITLE
Sleipnir-Colorful - fork of Sleipnir

### ISSUE THREAD

**Issue by RobZombie9043** [mmatyas/pegasus-theme-gallery-db#28]
Hi, created a new fork of the retro mega-Sleipnir theme using theme art and videos from the Colorful theme by viking.

https://github.com/RobZombie9043/retromega-sleipnir-colorful

**Comment by mmatyas** [comment]
Nice! I'm away at the moment, but I'll add this by the next week.

**Comment by mmatyas** [comment]
Ok, this should be online now. Sorry for the wait!

**Comment by RobZombie9043** [comment]
Hi again, 

I've recreated this theme now from scratch with much better animations and views to match the original Colorful theme. Could you please remove the original one and replace with this new version when you have a chance?

https://github.com/RobZombie9043/COLORFUL

**Comment by mmatyas** [comment]
Ok, updated, thanks!

**Comment by RobZombie9043** [comment]
Thank you, sorry I forgot to include screenshots in the theme.cfg and updated that now.

**Comment by mmatyas** [comment]
Ok, should be updated in a few minutes.
