### ISSUE TITLE
Nostalgia-Grid new theme

### ISSUE THREAD

**Issue by ZagonAb** [mmatyas/pegasus-theme-gallery-db#35]
Hello, it is a theme similar to the one provided by the Nintendo Switch interface for its retro games.  https://github.com/ZagonAb/Nostalgia-Grid

**Comment by mmatyas** [comment]
Thanks! I believe your `assets.screenshots` entry might be a bit off, could you double check?

**Comment by ZagonAb** [comment]
You are absolutely right. I have already updated the theme.cgf file.

**Comment by mmatyas** [comment]
Added, thanks!
