### ISSUE TITLE
Pegasus Boy Lite

### ISSUE THREAD

**Issue by tap0119** [mmatyas/pegasus-theme-gallery-db#37]
I'd like to add this theme I modified from Pegasus Boy https://github.com/tap0119/PegasusBoyLite

**Comment by mmatyas** [comment]
Thanks! However, your `theme.cfg` doesn't have any description or images in it, is that all right? You can take a look at other themes if you're looking for inspiration.

**Comment by tap0119** [comment]
I updated that file, let me know if everything looks good now

**Comment by mmatyas** [comment]
Just one typo: the screenshots are in the `assets` dir, but the config says it's under ˙.assets` (with a dot).

**Comment by tap0119** [comment]
Fixed

**Comment by mmatyas** [comment]
Added, thanks!
